version: "3.5"
services:
  nextjs-app:
    container_name: aginatech-ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
